Repository trimble-oss/website-modus.trimble.com, pull requests merged in 2022-05, with the labels that each got.

#105 Update community-tiger-teams.md
  content/community-tiger-teams.md
Labels: 1

#101 Add Plausible Analytics (no cookies!)
  layouts/partials/analytics.html
Labels: 1

#108 Feat: Add PurgeCSS (preparation for dark mode toggle)
  .cspell.json
  content/components/alerts.md
  content/components/toasts.md
  content/foundations-icon-definitions.md
  layouts/_default/baseof.html
  layouts/partials/icons/manage-debt.svg
  package-lock.json
  package.json
  postcss.config.js
Labels: 3, priority:medium

#112 Tweaks to GitHub Actions and GitHub configs
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  .github/dependabot.yml
  .github/pull_request_template.md
  .github/workflows/codeql-analysis.yml
  .github/workflows/spellcheck.yml
Labels: 1, priority:low, github_actions
